Server:
  Host: "http://127.0.0.1:8080/api/v1/monitor"
  Secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiZXhwIjoxNTkwMTU1OTYxLCJpc3MiOiJlbGtQb3J0ZXIifQ.cr8efy7N4TbsVPN0SDbTlnCFUNoXIhctr5ulQIFUlU8"

MySQLApplication:
  Tag: MySQL
  LoopTime: 10
  Timeout: 3
  HostPool:
    - "127.0.0.1:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"
    - "127.0.0.2:3306:mysql-test"

ElasticSearchApplication:
  Tag: ElasticSearch
  LoopTime: 10
  Timeout: 3
  HostPool:
    - "192.168.31.2:9200:warm-1"